<?php
/**
 * Stable per-visitor session key resolution.
 *
 * @package CartRebound
 */

declare( strict_types=1 );

namespace CartRebound\Tracking;

defined( 'ABSPATH' ) || exit;

use CartRebound\Models\CartSession;

/**
 * Resolves a stable, unguessable key that identifies a visitor's cart.
 *
 * The key is generated specifically for Cart Rebound, mirrored into both a
 * first-party cookie and the WooCommerce session, and never derived from a
 * predictable WordPress user or WooCommerce customer id. On login a guest row
 * is merged into the user's identity.
 *
 * @since 0.1.0
 */
final class SessionManager {

	/**
	 * First-party cookie name holding the stable key.
	 *
	 * @var string
	 */
	public const COOKIE = 'cart_rebound_ref';

	/**
	 * WooCommerce session slot used when the browser rejects our cookie.
	 *
	 * @var string
	 */
	private const WC_SESSION_KEY = 'cart_rebound_browser_id';

	/**
	 * Length of a generated alphanumeric browser identifier.
	 *
	 * @var int
	 */
	private const KEY_LENGTH = 64;

	/**
	 * Resolve the stable session key for the current visitor.
	 *
	 * @since 0.1.0
	 *
	 * @return string Empty string when no WooCommerce session exists yet.
	 */
	public function resolve_session_key(): string {
		$cookie = $this->read_cookie();

		if ( '' !== $cookie ) {
			return $cookie;
		}

		$key = $this->woocommerce_session_key();

		if ( '' === $key ) {
			return '';
		}

		$this->persist_cookie( $key );

		return $key;
	}

	/**
	 * Merge a guest's tracked cart into the user identity on login.
	 *
	 * @since 0.1.0
	 *
	 * @param int $user_id The user that just logged in.
	 * @return void
	 */
	public function merge_guest_into_user( int $user_id ): void {
		$key = $this->read_cookie();

		if ( '' === $key || $user_id <= 0 ) {
			return;
		}

		$row = CartSession::query()->where( 'session_key', '=', $key )->first();

		if ( ! is_array( $row ) || 0 !== (int) ( $row['user_id'] ?? 0 ) ) {
			return;
		}

		$update = array(
			'user_id'       => $user_id,
			'last_activity' => gmdate( 'Y-m-d H:i:s' ),
		);

		$user = get_userdata( $user_id );

		if ( false !== $user && '' === (string) ( $row['email'] ?? '' ) ) {
			$update['email']      = $user->user_email;
			$update['first_name'] = (string) get_user_meta( $user_id, 'first_name', true );
			$update['last_name']  = (string) get_user_meta( $user_id, 'last_name', true );
		}

		CartSession::update( (int) ( $row['id'] ?? 0 ), $update );
	}

	/**
	 * Forget the current visitor's tracking session after their cart converts.
	 *
	 * Best-effort: drops the WooCommerce session slot and expires the first-party
	 * cookie so the shopper's next cart opens a brand-new tracked row instead of
	 * reusing the just-converted key. Safe to call in any context — it no-ops when
	 * WooCommerce has no session or headers are already sent.
	 *
	 * @since 0.1.0
	 *
	 * @return void
	 */
	public function clear(): void {
		// Only retire the session from the shopper's own front-end request. On a
		// wp-admin order edit or a cron/webhook status change the current cookie
		// and WooCommerce session belong to someone else (or no one), and
		// CartTracker archives the converted key on the next cart regardless.
		if ( is_admin() || wp_doing_cron() ) {
			return;
		}

		// Once output has started the cookie can no longer be expired; bail before
		// touching the WooCommerce session too, so the cookie and the session slot
		// can never diverge (the cookie is read first on the next request).
		if ( headers_sent() ) {
			return;
		}

		if ( function_exists( 'WC' ) ) {
			$wc = WC();

			if ( is_object( $wc ) && null !== $wc->session ) {
				$wc->session->set( self::WC_SESSION_KEY, null );
			}
		}

		unset( $_COOKIE[ self::COOKIE ] );

		setcookie( self::COOKIE, '', $this->cookie_options( time() - DAY_IN_SECONDS ) );
	}

	/**
	 * Resolve or create the plugin-specific key stored in WooCommerce's session.
	 *
	 * @since 0.1.0
	 *
	 * @return string
	 */
	private function woocommerce_session_key(): string {
		if ( ! function_exists( 'WC' ) ) {
			return '';
		}

		$wc = WC();

		if ( ! is_object( $wc ) || null === $wc->session ) {
			return '';
		}

		$stored = $wc->session->get( self::WC_SESSION_KEY );
		$key    = is_string( $stored ) ? $this->validated_key( $stored ) : '';

		if ( '' !== $key ) {
			return $key;
		}

		$key = wp_generate_password( self::KEY_LENGTH, false, false );
		$wc->session->set( self::WC_SESSION_KEY, $key );

		return $key;
	}

	/**
	 * Read the first-party cookie value (sanitised).
	 *
	 * @since 0.1.0
	 *
	 * @return string
	 */
	private function read_cookie(): string {
		if ( ! isset( $_COOKIE[ self::COOKIE ] ) || ! is_string( $_COOKIE[ self::COOKIE ] ) ) {
			return '';
		}

		// Identifier cookie; unslashed + strictly validated on use, no nonce
		// applies to a read-only browser reference.
		return $this->validated_key( sanitize_text_field( wp_unslash( $_COOKIE[ self::COOKIE ] ) ) );
	}

	/**
	 * Accept only keys generated by this class's alphanumeric format.
	 *
	 * A forged short value such as a numeric WordPress user id must never become
	 * a database session key.
	 *
	 * @since 0.1.0
	 *
	 * @param string $value Candidate key.
	 * @return string Valid key, or an empty string.
	 */
	private function validated_key( string $value ): string {
		return 1 === preg_match( '/\A[A-Za-z0-9]{64}\z/', $value ) ? $value : '';
	}

	/**
	 * Persist the stable key into a ~30-day first-party cookie.
	 *
	 * @since 0.1.0
	 *
	 * @param string $value The stable key to store.
	 * @return void
	 */
	private function persist_cookie( string $value ): void {
		if ( headers_sent() ) {
			return;
		}

		setcookie( self::COOKIE, $value, $this->cookie_options( time() + ( 30 * DAY_IN_SECONDS ) ) );
	}

	/**
	 * Build the cookie option array shared by the set and clear paths.
	 *
	 * Keeping one definition guarantees the expiring cookie carries the exact
	 * path/secure/samesite scope the original was set with — a mismatch would
	 * leave the browser holding the old cookie.
	 *
	 * @since 0.1.0
	 *
	 * @param int $expires Unix expiry timestamp.
	 * @return array<string, mixed>
	 */
	private function cookie_options( int $expires ): array {
		return array(
			'expires'  => $expires,
			'path'     => defined( 'COOKIEPATH' ) && '' !== COOKIEPATH ? COOKIEPATH : '/',
			'secure'   => is_ssl(),
			'httponly' => true,
			'samesite' => 'Lax',
		);
	}
}
